name: GCP CI/CD Pipeline to GKE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: your-gcp-project-id
  GKE_CLUSTER: app-management-gke-cluster
  GCP_REGION: us-central1
  AR_REPO: app-registry
  IMAGE_NAME: app-management-system
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permission:
      contents: 'read'
      id-token: 'write'

    steps:
    - namee: Checkout Code
      uses: actions/checkout@v4

    - name: Set up GCP Authentication
      uses: 'google-github-action/auth@v2'
      with:
        workload_identitiy_provider: projects/ID/locations/global/workloadIdentityPools/POOL_NAME/providers/PROVIDER_ID
        service_account: your-service-account@your-gcp-project-id.iam.gserviceaccount.com

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure Docker to use Artifact Registry
      run: gcloud auth configure-docker ${GCP_REGION}-docker.pkg.dev

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          ${{ GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GCP_REGION }}

    - name: Update Kubernetes Manifest
      run: |
        FULL_IMAGE_PATH="${{ GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"

        sed -i 's|YOUR_REGISTRY_PATH/app-management-system:latest|'$FULL_IMAGE_PATH'|g' ./manifests/k8s-deployment.yaml

    - name: Deploy to GKE
      run: |
        kubectl apply -f ./manifests/k8s-deployment.yaml
        kubectl apply -f ./manifests/k8s-service.yaml

    - name: Verify Deployment
      run: kubectl rollout status deployment/app-management-deployment
